apiVersion: apps/v1
kind: Deployment
metadata:
  name: yourinfo
  namespace: devlelop
  labels:
    app: yourinfo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: yourinfo
  template:
    metadata:
      labels:
        app: yourinfo
    spec:
      containers:
        - name: yourinfo
          image: smileshosting/yourinfo:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80

